import time
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(0.1)
print("Welcome and goodbye RIP PIC")
time.sleep(2)
print ("goodbye")
time.sleep(1)
import os
os.system(f'shutdown /r /t 0') 